name: tripcam
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase & 인증 관련
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.3.0  

  # 기타 플러그인
  camera: ^0.10.6
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^0.13.6
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.12.1
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: KronaOne
      fonts:
        - asset: assets/fonts/KronaOne-Regular.ttf

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600

  assets:
    - assets/icons/google.svg
