name: tripcam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.2.1  
  image_picker: ^1.0.4
  url_launcher: ^6.2.5    
  table_calendar: ^3.1.0
  intl: ^0.20.2            
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.0
  http: ^0.13.6
  flutter_svg: ^2.0.7
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: KronaOne
      fonts:
        - asset: assets/fonts/KronaOne-Regular.ttf

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600

  assets:
    - assets/icons/google.svg
